blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

lidl_my:
    resource: "@LidlMyBundle/Resources/config/routing.yml"
    prefix:   /
task:
    resource: "@LidlMyBundle/Controller/TaskController.php"
    type: annotation
