parameters:
#    lidl_lidl.example.class: Lidl\Bundle\LidlBundle\Example

services:
#    lidl_lidl.example:
#        class: %lidl_lidl.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
